<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="LAPTOP-G3GAB2EO" name="pytest" skipped="0" tests="1" time="6.521" timestamp="2020-07-28T14:15:51.233579"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\_pytest\main.py&quot;, line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\_pytest\main.py&quot;, line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\_pytest\runner.py&quot;, line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\_pytest\runner.py&quot;, line 94, in runtestprotocol
    rep = call_and_report(item, &quot;setup&quot;, log)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\_pytest\runner.py&quot;, line 188, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;E:\virtualenv\echo2.X_autotest\lib\site-packages\pluggy\callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;E:\YOYO\echo2.X_autotest\conftest.py&quot;, line 51, in pytest_runtest_makereport
    capture_screenshots(case_name)
  File &quot;E:\YOYO\echo2.X_autotest\conftest.py&quot;, line 95, in capture_screenshots
    raise NameError(&apos;没有初始化测试报告目录&apos;)
NameError: 没有初始化测试报告目录</error></testcase></testsuite></testsuites>